version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.19
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Run unit tests
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES
      - run:
          name: Run build
          command: make build
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

  coverage:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: Generate coverage report
          command: make coverage
      - run:
          name: Upload coverage report
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  all:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - coverage:
          requires:
            - build
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
