# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Release Assets
on:
  release:
    types: [published]

jobs:

  build-release-x86_64:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: |
             subdir/go.sum
             tools/go.sum
      - name: Build and archive x86_64 distribution
        run: make zip-x86_64
      - name: Publish x86_64 release on GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          file=/tmp/newrelic-lambda-extension.x86_64.zip
          echo "uploading $file to release $TAG"
          gh release upload "$TAG" "$file"
  
  build-release-arm:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: |
             subdir/go.sum
             tools/go.sum
      - name: Build and archive arm distribution
        run: make zip-arm64
      - name: Publish zip-arm64 release on GitHub
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          file=/tmp/newrelic-lambda-extension.arm64.zip
          echo "uploading $file to release $TAG"
          gh release upload "$TAG" "$file"
